// import React from 'react'; // In newer versions of React(since React 17) it is not necessary to import React in files where JSX is used
import './app.css'
import Dice from './Components/Dice'
import { useState } from 'react';
import { nanoid } from 'nanoid'


export default function App()
{
  // State variable to hold on random dice values array
  const[diceValues,setdiceValues] = useState(allNewDice())

  // To generate new values for dice
  function generateNewDie()
  {
    return{
      value:Math.ceil(Math.random() * 6),
      isHeld:false,
      id:nanoid()
    }
    
  }

  // Function to generate random number and store it an array and manage by state function
  function allNewDice()
  {
    const result = [];
    for(let i=0;i<10;i++)
    {
      result.push(generateNewDie())
    }
      return result
  }

  // function to hold values after getting randomly generated by clicking roll button
  function rollDice()
  {
    setdiceValues(oldDice => oldDice.map(die =>
      {
        return die.isHeld ?
              die:generateNewDie()
               
      }))
  }
  
  // Getting the clicked value ID's to change their isHeld property to change the background
  function holdDice(id) {
    setdiceValues(oldDice => oldDice.map(die => {
        return die.id === id ? 
            {...die, isHeld: !die.isHeld} :
            die
    }))
    
}

  // to iterate over random dice value array using map and rendering it in Dice Component
  const diceElements = diceValues.map((value,index) => <Dice value={value.value} isHeld={value.isHeld} key={index} holdDice={() => holdDice(value.id)}/>)

  return(
    <>
    {/* Main element for which our Dice component will render */}
      <main>
      <h1 className="title">Tenzies</h1>
            <p className="instructions">Roll until all dice are the same. Click each die to freeze it at its current value between rolls.</p>
        {/* Dice Container of our Dice Component */}
        <div className='dice-container'>
          {diceElements}
        </div>
        <button onClick={rollDice}>Roll</button>
      </main>
    </>
  )
}