// import React from 'react'; // In newer versions of React(since React 17) it is not necessary to import React in files where JSX is used
import './app.css'
import Dice from './Components/Dice'
import { useState } from 'react';
import { nanoid } from 'nanoid'


export default function App()
{
  // State variable to hold on random dice values array
  const[diceValues,setdiceValues] = useState(allNewDice())

  // console.log(diceValues)

  // Function to generate random number and store it an array and manage by state function
  function allNewDice()
  {
    const result = [];
    for(let i=0;i<10;i++)
    {
      const randomNum = {
            value:Math.ceil(Math.random() * 6),
            isHeld:false,
            id:nanoid()
          }
      result.push(randomNum)
    }
      return result
  }

  // function to hold values after getting randomly generated by clicking roll button
  function rollDice()
  {
    setdiceValues(allNewDice())
  }
  
  function holdDice()
  {
    console.log(diceValues.id)
  }

  holdDice()

  // to iterate over random dice value array using map and rendering it in Dice Component
  const diceElements = diceValues.map((value,index) => <Dice value={value.value} isHeld={value.isHeld} key={index} holdDice={() => holdDice(value.id)}/>)

  return(
    <>
    {/* Main element for which our Dice component will render */}
      <main>
        {/* Dice Container of our Dice Component */}
        <div className='dice-container'>
          {diceElements}
        </div>
        <button onClick={rollDice}>Roll</button>
      </main>
    </>
  )
}